
name: 'GitHub Actions Weekly Reader'

on:
  push:
  schedule:
    - cron: '0 18 * * 1'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1    
      - name: 'Run code'
        run: bash ./index.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Weekly Reader (${{env.REPORT_DATE}})
          body: file://result.html
          to: zhengfuchao2008@126.com
          from: GitHub Actions
          content_type: text/html
